### ISSUE TITLE
Parameter for multi libraries

### ISSUE THREAD

**Issue by ptranvan** [Malfoy/BWISE#1]
Hi!

I plan to try your assembler for my data which are composed of 3 PE libraries:

- 180
- 350
- 550

I am asking your help how to use your assembler for this kind of data.

1) The assembler can handle multiple libraries ?

2) If yes, it seems that I have to use the -x option: Does it has to be formated in interleaved format ?

3) Can I use -x 3 times or have to merge the 3 libraries. 

Thanks for your support.

**Comment by Malfoy** [comment]
Hi!
For now the parser is only able to take one, interleaved PE file.
My advice for now is to cat your three files and give it to BWISE with -x.
I will try to add a file of files option in order to facilitate this kind of problems.
