### ISSUE TITLE
Problem with binary compilation of BWISE.

### ISSUE THREAD

**Issue by nityendra21** [Malfoy/BWISE#18]
Hi, I'm facing an issue when compiling BWISE at step one itself, encountering the error. 
`I put binaries in /home/igib/visanu2/BWISE/bin
PHASE ONE LAUNCHER: BWISE
there was a problem with binary compilation, check logs
` 
The OS I'm using is Ubuntu 22.04 LTS, CMAKE version 3.22.1, Make version 4.3 and GCC version 11.2.0 in a Python 3.7.13 environment.

**Comment by odethier-ulb** [comment]
Hello, can you copy/paste the content of the file _/home/igib/visanu2/BWISE/src/logCompile.txt_ ?

**Comment by nityendra21** [comment]
Sure. 
`g++ -o n50.o -c N50.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o sequencesToNumbers.o -c sequencesToNumbers.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o numbersToSequences.o -c numbersToSequences.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o numbersFilter.o -c numbersFilter.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o simulator.o -c simulator.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o path_counter.o -c path_counter.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o maximal_sr.o -c Maximal_SR.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o crush_bulle.o -c crush_bulle.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
In file included from Maximal_SR.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [makefile:48: maximal_sr.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from path_counter.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [makefile:30: path_counter.o] Error 1
simulator.cpp: In function ‘uint32_t xs(uint32_t&)’:
simulator.cpp:15:33: warning: operation on ‘y’ may be undefined [-Wsequence-point]
   15 |         y^=(y<<13); y^=(y>>17);y=(y^=(y<<15)); return y;
      |                                ~^~~~~~~~~~~~~
simulator.cpp:15:33: warning: operation on ‘y’ may be undefined [-Wsequence-point]
g++ -o n50 n50.o -flto -fopenmp -lz
g++ -o sequencesToNumbers sequencesToNumbers.o -flto -fopenmp -lz
g++ -o numbersToSequences numbersToSequences.o -flto -fopenmp -lz
g++ -o numbersFilter numbersFilter.o -flto -fopenmp -lz
g++ -o simulator simulator.o -flto -fopenmp -lz
g++ -o path_counter.o -c path_counter.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o maximal_sr.o -c Maximal_SR.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o crush_bulle crush_bulle.o -flto -fopenmp -lz
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [makefile:60: n50] Error 1
make: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [makefile:33: crush_bulle] Error 1
make: *** [makefile:63: simulator] Error 1
collect2: error: ld returned 1 exit status
make: *** [makefile:81: numbersFilter] Error 1
collect2: error: ld returned 1 exit status
make: *** [makefile:87: numbersToSequences] Error 1
collect2: error: ld returned 1 exit status
make: *** [makefile:69: sequencesToNumbers] Error 1
In file included from Maximal_SR.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
In file included from path_counter.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [makefile:48: maximal_sr.o] Error 1
make: *** [makefile:30: path_counter.o] Error 1
g++ -o n50 n50.o -flto -fopenmp -lz
g++ -o sequencesToNumbers sequencesToNumbers.o -flto -fopenmp -lz
g++ -o numbersToSequences numbersToSequences.o -flto -fopenmp -lz
g++ -o numbersFilter numbersFilter.o -flto -fopenmp -lz
g++ -o simulator simulator.o -flto -fopenmp -lz
g++ -o path_counter.o -c path_counter.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o maximal_sr.o -c Maximal_SR.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o crush_bulle crush_bulle.o -flto -fopenmp -lz
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld/usr/bin/ld: cannot find : cannot find -lz-lz: : No such file or directoryNo such file or directory

/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [makefile:33: crush_bulle] Error 1
make: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [makefile:81: numbersFilter] Error 1
make: *** [makefile:69: sequencesToNumbers] Error 1
make: *** [makefile:60: n50] Error 1
make: *** [makefile:87: numbersToSequences] Error 1
make: *** [makefile:63: simulator] Error 1
In file included from Maximal_SR.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
In file included from path_counter.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [makefile:48: maximal_sr.o] Error 1
make: *** [makefile:30: path_counter.o] Error 1
g++ -o n50 n50.o -flto -fopenmp -lz
g++ -o sequencesToNumbers sequencesToNumbers.o -flto -fopenmp -lz
g++ -o numbersToSequences numbersToSequences.o -flto -fopenmp -lz
g++ -o numbersFilter numbersFilter.o -flto -fopenmp -lz
g++ -o simulator simulator.o -flto -fopenmp -lz
g++ -o path_counter.o -c path_counter.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o maximal_sr.o -c Maximal_SR.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o crush_bulle crush_bulle.o -flto -fopenmp -lz
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld/usr/bin/ld: cannot find : cannot find -lz-lz: : No such file or directoryNo such file or directory

/usr/bin/ld: cannot find -lz: No such file or directory
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [makefile:69: sequencesToNumbers] Error 1
make: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make: *** [makefile:63: simulator] Error 1
make: *** [makefile:81: numbersFilter] Error 1
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [makefile:60: n50] Error 1
make: *** [makefile:87: numbersToSequences] Error 1
collect2: error: ld returned 1 exit status
make: *** [makefile:33: crush_bulle] Error 1
In file included from path_counter.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [makefile:30: path_counter.o] Error 1
In file included from Maximal_SR.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [makefile:48: maximal_sr.o] Error 1
g++ -o n50 n50.o -flto -fopenmp -lz
g++ -o sequencesToNumbers sequencesToNumbers.o -flto -fopenmp -lz
g++ -o numbersToSequences numbersToSequences.o -flto -fopenmp -lz
g++ -o numbersFilter numbersFilter.o -flto -fopenmp -lz
g++ -o simulator simulator.o -flto -fopenmp -lz
g++ -o path_counter.o -c path_counter.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o maximal_sr.o -c Maximal_SR.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o crush_bulle crush_bulle.o -flto -fopenmp -lz
/usr/bin/ld/usr/bin/ld: cannot find : cannot find -lz-lz: : No such file or directoryNo such file or directory

/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [makefile:87: numbersToSequences] Error 1
make: *** Waiting for unfinished jobs....
make: *** [makefile:81: numbersFilter] Error 1
make: *** [makefile:60: n50] Error 1
make: *** [makefile:63: simulator] Error 1
make: *** [makefile:69: sequencesToNumbers] Error 1
collect2: error: ld returned 1 exit status
make: *** [makefile:33: crush_bulle] Error 1
In file included from path_counter.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
In file included from Maximal_SR.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
compilation terminated.
make: *** [makefile:48: maximal_sr.o] Error 1
make: *** [makefile:30: path_counter.o] Error 1
g++ -o n50 n50.o -flto -fopenmp -lz
g++ -o sequencesToNumbers sequencesToNumbers.o -flto -fopenmp -lz
g++ -o numbersToSequences numbersToSequences.o -flto -fopenmp -lz
g++ -o numbersFilter numbersFilter.o -flto -fopenmp -lz
g++ -o simulator simulator.o -flto -fopenmp -lz
g++ -o path_counter.o -c path_counter.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o maximal_sr.o -c Maximal_SR.cpp -Wall  -Ofast -std=c++11  -flto -pipe -funit-at-a-time  -Wfatal-errors -fopenmp -lz
g++ -o crush_bulle crush_bulle.o -flto -fopenmp -lz
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory/usr/bin/ld
: cannot find -lz: No such file or directory
/usr/bin/ld: cannot find -lz: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [makefile:60: n50] Error 1
make: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [makefile:69: sequencesToNumbers] Error 1
make: *** [makefile:33: crush_bulle] Error 1
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [makefile:63: simulator] Error 1
collect2: error: ld returned 1 exit status
make: *** [makefile:81: numbersFilter] Error 1
make: *** [makefile:87: numbersToSequences] Error 1
In file included from Maximal_SR.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [makefile:48: maximal_sr.o] Error 1
In file included from path_counter.cpp:12:
zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [makefile:30: path_counter.o] Error 1`

**Comment by nityendra21** [comment]
Ok, so through this log I realized I lacked the zlib library files and upon installing them with `apt-get install zlib1g-dev,` BWISE compilation was successful. Thanks!

**Comment by odethier-ulb** [comment]
Yes I was going to write it but you were faster than me :)
