### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by ptranvan** [Malfoy/BWISE#3]
Hi,

Do you have some statistics regarding the running time of the assembler with how many CPU associated ?

**Comment by rchikhi** [comment]
It does not seem that the authors have published that information, yet I believe that their have a manuscript in preparation. The pipeline is made of many steps, one of them is the Bcalm software, that has significant, yet sublinear, parallel speed-up. I do not know about the other steps.

**Comment by jflot** [comment]
It is difficult to answer this question as it completely depends on the size of the datasets and how difficult they are to assemble - i.e., a complex genome structure with intermediate-level heterozygosity will yield highly fragmented DBG on which read mapping will take much longer than a genome of the same size for which the DBG has larger unitigs. Details benchmarks will be included in the BWISE publication.
