### ISSUE TITLE
What is the final file ?

### ISSUE THREAD

**Issue by ptranvan** [Malfoy/BWISE#4]
Hi,

I have run the assembly and apparently it works without error (see log below).
But I would like to know what is the name of the final file (the contigs) ?

`
./Bwise.py -x Sm2.trim.180.pair12.fastq -k 300 -t 30 -o out

* This is BWISE - High order De Bruijn graph assembler *

Binaries are in: /scratch/local/monthly/ptranvan/BWISE/bin
The command line was: ./Bwise.py -x Sm2.trim.180.pair12.fastq -k 300 -t 30 -o out
Results will be stored in:  /scratch/local/monthly/ptranvan/BWISE/out

[08:49:30 20/04/2017] --> Starting Read Correction with Bloocoo...
        Correction step 1
                /scratch/local/monthly/ptranvan/BWISE/bin/Bloocoo32 -file /scratch/local/monthly/ptranvan/BWISE/Sm2.trim.180.pair12.fastq  -slow -kmer
-size 31 -nbits-bloom 24  -out reads_corrected1.fa -nb-cores 30
        Correction step 2
                /scratch/local/monthly/ptranvan/BWISE/bin/Bloocoo64 -file /scratch/local/monthly/ptranvan/BWISE/out/reads_corrected1.fa  -slow -kmer-s
ize 63 -nbits-bloom 24  -out reads_corrected2.fa -nb-cores 30
        Correction step 3
                /scratch/local/monthly/ptranvan/BWISE/bin/Bloocoo128 -file /scratch/local/monthly/ptranvan/BWISE/out/reads_corrected2.fa  -slow -kmer-
size 95 -nbits-bloom 24  -out reads_corrected3.fa -nb-cores 30
        Correction step 4
                /scratch/local/monthly/ptranvan/BWISE/bin/Bloocoo128 -file /scratch/local/monthly/ptranvan/BWISE/out/reads_corrected3.fa  -slow -kmer-size 127 -nbits-bloom 24  -out reads_corrected4.fa -nb-cores 30
                        ln -fs /scratch/local/monthly/ptranvan/BWISE/out/reads_corrected4.fa  /scratch/local/monthly/ptranvan/BWISE/out/reads_corrected.fa

[13:35:31 20/04/2017] --> Correction Done
Correction took:  4:46:01

[13:35:31 20/04/2017] --> Starting Graph construction and Super Reads generation...
        #Graph 1: Construction... 
                /scratch/local/monthly/ptranvan/BWISE/bin/bcalm -in /scratch/local/monthly/ptranvan/BWISE/out/bankBcalm.txt -kmer-size 51 -abundance-min 2 -out /scratch/local/monthly/ptranvan/BWISE/out/out  -nb-cores 30
                 #Cleaning... 
                        /scratch/local/monthly/ptranvan/BWISE/bin/kMILL out.unitigs.fa 50 49
                        /scratch/local/monthly/ptranvan/BWISE/bin/tipCleaner out_out.unitigs.fa.fa 50 101
                        /scratch/local/monthly/ptranvan/BWISE/bin/kMILL tiped.fa 50 49
                        mv out_tiped.fa.fa dbg51.fa
        #Read mapping with BGREAT... 
                /scratch/local/monthly/ptranvan/BWISE/bin/bgreat -M -k 51 -i 10  -x reads_corrected.fa  -g dbg51.fa -t 30 -a 63 -m 0 -e 100
                /scratch/local/monthly/ptranvan/BWISE/bin/numbersFilter paths 2 cleanedPaths_51 2 dbg51.fa 51
                /scratch/local/monthly/ptranvan/BWISE/bin/run_K2000.sh cleanedPaths_51 dbg51.fa 51 compacted_unitigs_k51.gfa compacted_unitigs_k51.fa
        #Graph 2: Construction... 
                /scratch/local/monthly/ptranvan/BWISE/bin/bcalm -in /scratch/local/monthly/ptranvan/BWISE/out/compacted_unitigs_k51.fa -kmer-size 101 -abundance-min 1 -out /scratch/local/monthly/ptranvan/BWISE/out/out  -nb-cores 30
                 #Cleaning... 
                        /scratch/local/monthly/ptranvan/BWISE/bin/kMILL out.unitigs.fa 100 99
                        /scratch/local/monthly/ptranvan/BWISE/bin/tipCleaner out_out.unitigs.fa.fa 100 151
                        /scratch/local/monthly/ptranvan/BWISE/bin/kMILL tiped.fa 100 99
                        mv out_tiped.fa.fa dbg101.fa
        #Read mapping with BGREAT... 
                /scratch/local/monthly/ptranvan/BWISE/bin/bgreat -M -k 101 -i 10  -x reads_corrected.fa  -g dbg101.fa -t 30 -a 63 -m 0 -e 100
                /scratch/local/monthly/ptranvan/BWISE/bin/numbersFilter paths 2 cleanedPaths_101 2 dbg101.fa 101
                /scratch/local/monthly/ptranvan/BWISE/bin/run_K2000.sh cleanedPaths_101 dbg101.fa 101 compacted_unitigs_k101.gfa compacted_unitigs_k101.fa
 #Graph 3: Construction... 
                /scratch/local/monthly/ptranvan/BWISE/bin/bcalm -in /scratch/local/monthly/ptranvan/BWISE/out/compacted_unitigs_k101.fa -kmer-size 151 -abundance-min 1 -out /scratch/local/monthly/ptranvan/BWISE/out/out  -nb-cores 30
                 #Cleaning... 
                        /scratch/local/monthly/ptranvan/BWISE/bin/kMILL out.unitigs.fa 150 149
                        /scratch/local/monthly/ptranvan/BWISE/bin/tipCleaner out_out.unitigs.fa.fa 150 201
                        /scratch/local/monthly/ptranvan/BWISE/bin/kMILL tiped.fa 150 149
                        mv out_tiped.fa.fa dbg151.fa
        #Read mapping with BGREAT... 
                /scratch/local/monthly/ptranvan/BWISE/bin/bgreat -M -k 151 -i 10  -x reads_corrected.fa  -g dbg151.fa -t 30 -a 63 -m 0 -e 100
                /scratch/local/monthly/ptranvan/BWISE/bin/numbersFilter paths 2 cleanedPaths_151 2 dbg151.fa 151
                /scratch/local/monthly/ptranvan/BWISE/bin/run_K2000.sh cleanedPaths_151 dbg151.fa 151 compacted_unitigs_k151.gfa compacted_unitigs_k151.fa
        #Graph 4: Construction... 
                /scratch/local/monthly/ptranvan/BWISE/bin/bcalm -in /scratch/local/monthly/ptranvan/BWISE/out/compacted_unitigs_k151.fa -kmer-size 201 -abundance-min 1 -out /scratch/local/monthly/ptranvan/BWISE/out/out  -nb-cores 30
                 #Cleaning... 
                        /scratch/local/monthly/ptranvan/BWISE/bin/kMILL out.unitigs.fa 200 199
                        /scratch/local/monthly/ptranvan/BWISE/bin/tipCleaner out_out.unitigs.fa.fa 200 251
                        /scratch/local/monthly/ptranvan/BWISE/bin/kMILL tiped.fa 200 199
                        mv out_tiped.fa.fa dbg201.fa
        #Read mapping with BGREAT... 
                /scratch/local/monthly/ptranvan/BWISE/bin/bgreat -M -k 201 -i 10  -x reads_corrected.fa  -g dbg201.fa -t 30 -a 63 -m 0 -e 100
                /scratch/local/monthly/ptranvan/BWISE/bin/numbersFilter paths 2 cleanedPaths_201 2 dbg201.fa 201
                /scratch/local/monthly/ptranvan/BWISE/bin/run_K2000.sh cleanedPaths_201 dbg201.fa 201 compacted_unitigs_k201.gfa compacted_unitigs_k201.fa
        #Graph 5: Construction... 
                /scratch/local/monthly/ptranvan/BWISE/bin/bcalm -in /scratch/local/monthly/ptranvan/BWISE/out/compacted_unitigs_k201.fa -kmer-size 251 -abundance-min 1 -out /scratch/local/monthly/ptranvan/BWISE/out/out  -nb-cores 30
                 #Cleaning... 
                        /scratch/local/monthly/ptranvan/BWISE/bin/kMILL out.unitigs.fa 250 249
                        /scratch/local/monthly/ptranvan/BWISE/bin/tipCleaner out_out.unitigs.fa.fa 250 301
                        /scratch/local/monthly/ptranvan/BWISE/bin/kMILL tiped.fa 250 249
                        mv out_tiped.fa.fa dbg251.fa
        #Read mapping with BGREAT... 
                /scratch/local/monthly/ptranvan/BWISE/bin/bgreat -M -k 251 -i 10  -x reads_corrected.fa  -g dbg251.fa -t 30 -a 63 -m 0 -e 100
                /scratch/local/monthly/ptranvan/BWISE/bin/numbersFilter paths 2 cleanedPaths_251 2 dbg251.fa 251
                /scratch/local/monthly/ptranvan/BWISE/bin/run_K2000.sh cleanedPaths_251 dbg251.fa 251 compacted_unitigs_k251.gfa compacted_unitigs_k251.fa
[08:34:52 25/04/2017] --> Done!
Graph Construction took:  114:59:20

The end !
BWISE assembly took:  119:45:22
`

**Comment by jflot** [comment]
In your log file, the final file that contains the contigs is compacted_unitigs_k251.fa (whereas compacted_unitigs_k251.gfa contains the corresponding GFA contig graph).
